/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuMilkshakesRouteImport } from './routes/menu.milkshakes'
import { Route as MenuHotDessertsRouteImport } from './routes/menu.hot-desserts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuMilkshakesRoute = MenuMilkshakesRouteImport.update({
  id: '/menu/milkshakes',
  path: '/menu/milkshakes',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuHotDessertsRoute = MenuHotDessertsRouteImport.update({
  id: '/menu/hot-desserts',
  path: '/menu/hot-desserts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu/hot-desserts': typeof MenuHotDessertsRoute
  '/menu/milkshakes': typeof MenuMilkshakesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu/hot-desserts': typeof MenuHotDessertsRoute
  '/menu/milkshakes': typeof MenuMilkshakesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu/hot-desserts': typeof MenuHotDessertsRoute
  '/menu/milkshakes': typeof MenuMilkshakesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/menu/hot-desserts' | '/menu/milkshakes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/menu/hot-desserts' | '/menu/milkshakes'
  id: '__root__' | '/' | '/menu/hot-desserts' | '/menu/milkshakes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuHotDessertsRoute: typeof MenuHotDessertsRoute
  MenuMilkshakesRoute: typeof MenuMilkshakesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/milkshakes': {
      id: '/menu/milkshakes'
      path: '/menu/milkshakes'
      fullPath: '/menu/milkshakes'
      preLoaderRoute: typeof MenuMilkshakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/hot-desserts': {
      id: '/menu/hot-desserts'
      path: '/menu/hot-desserts'
      fullPath: '/menu/hot-desserts'
      preLoaderRoute: typeof MenuHotDessertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuHotDessertsRoute: MenuHotDessertsRoute,
  MenuMilkshakesRoute: MenuMilkshakesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
